---
services:
  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: gift_card_timescaledb
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: '-E UTF8 --locale=en_US.UTF-8'
    volumes:
      - timescale_data:/home/postgres/pgdata/data
      - ./database/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: gift_card_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: redis
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  timescale_data:
  redis_data:
